export type Code = {[key: number]: string}
export const codes: Code = {
  0: $localize`Unknown`,
  1000: $localize`Clear, Sunny`,
  1100: $localize`Mostly Clear`,
  1101: $localize`Partly Cloudy`,
  1102: $localize`Mostly Cloudy`,
  1001: $localize`Cloudy`,
  1103: $localize`Partly Cloudy and Mostly Clear`,
  2100: $localize`Light Fog`,
  2101: $localize`Mostly Clear and Light Fog`,
  2102: $localize`Partly Cloudy and Light Fog`,
  2103: $localize`Mostly Cloudy and Light Fog`,
  2106: $localize`Mostly Clear and Fog`,
  2107: $localize`Partly Cloudy and Fog`,
  2108: $localize`Mostly Cloudy and Fog`,
  2000: $localize`Fog`,
  4204: $localize`Partly Cloudy and Drizzle`,
  4203: $localize`Mostly Clear and Drizzle`,
  4205: $localize`Mostly Cloudy and Drizzle`,
  4000: $localize`Drizzle`,
  4200: $localize`Light Rain`,
  4213: $localize`Mostly Clear and Light Rain`,
  4214: $localize`Partly Cloudy and Light Rain`,
  4215: $localize`Mostly Cloudy and Light Rain`,
  4209: $localize`Mostly Clear and Rain`,
  4208: $localize`Partly Cloudy and Rain`,
  4210: $localize`Mostly Cloudy and Rain`,
  4001: $localize`Rain`,
  4211: $localize`Mostly Clear and Heavy Rain`,
  4202: $localize`Partly Cloudy and Heavy Rain`,
  4212: $localize`Mostly Cloudy and Heavy Rain`,
  4201: $localize`Heavy Rain`,
  5115: $localize`Mostly Clear and Flurries`,
  5116: $localize`Partly Cloudy and Flurries`,
  5117: $localize`Mostly Cloudy and Flurries`,
  5001: $localize`Flurries`,
  5100: $localize`Light Snow`,
  5102: $localize`Mostly Clear and Light Snow`,
  5103: $localize`Partly Cloudy and Light Snow`,
  5104: $localize`Mostly Cloudy and Light Snow`,
  5122: $localize`Drizzle and Light Snow`,
  5105: $localize`Mostly Clear and Snow`,
  5106: $localize`Partly Cloudy and Snow`,
  5107: $localize`Mostly Cloudy and Snow`,
  5000: $localize`Snow`,
  5101: $localize`Heavy Snow`,
  5119: $localize`Mostly Clear and Heavy Snow`,
  5120: $localize`Partly Cloudy and Heavy Snow`,
  5121: $localize`Mostly Cloudy and Heavy Snow`,
  5110: $localize`Drizzle and Snow`,
  5108: $localize`Rain and Snow`,
  5114: $localize`Snow and Freezing Rain`,
  5112: $localize`Snow and Ice Pellets`,
  6000: $localize`Freezing Drizzle`,
  6003: $localize`Mostly Clear and Freezing drizzle`,
  6002: $localize`Partly Cloudy and Freezing drizzle`,
  6004: $localize`Mostly Cloudy and Freezing drizzle`,
  6204: $localize`Drizzle and Freezing Drizzle`,
  6206: $localize`Light Rain and Freezing Drizzle`,
  6205: $localize`Mostly Clear and Light Freezing Rain`,
  6203: $localize`Partly Cloudy and Light Freezing Rain`,
  6209: $localize`Mostly Cloudy and Light Freezing Rain`,
  6200: $localize`Light Freezing Rain`,
  6213: $localize`Mostly Clear and Freezing Rain`,
  6214: $localize`Partly Cloudy and Freezing Rain`,
  6215: $localize`Mostly Cloudy and Freezing Rain`,
  6001: $localize`Freezing Rain`,
  6212: $localize`Drizzle and Freezing Rain`,
  6220: $localize`Light Rain and Freezing Rain`,
  6222: $localize`Rain and Freezing Rain`,
  6207: $localize`Mostly Clear and Heavy Freezing Rain`,
  6202: $localize`Partly Cloudy and Heavy Freezing Rain`,
  6208: $localize`Mostly Cloudy and Heavy Freezing Rain`,
  6201: $localize`Heavy Freezing Rain`,
  7110: $localize`Mostly Clear and Light Ice Pellets`,
  7111: $localize`Partly Cloudy and Light Ice Pellets`,
  7112: $localize`Mostly Cloudy and Light Ice Pellets`,
  7102: $localize`Light Ice Pellets`,
  7108: $localize`Mostly Clear and Ice Pellets`,
  7107: $localize`Partly Cloudy and Ice Pellets`,
  7109: $localize`Mostly Cloudy and Ice Pellets`,
  7000: $localize`Ice Pellets`,
  7105: $localize`Drizzle and Ice Pellets`,
  7106: $localize`Freezing Rain and Ice Pellets`,
  7115: $localize`Light Rain and Ice Pellets`,
  7117: $localize`Rain and Ice Pellets`,
  7103: $localize`Freezing Rain and Heavy Ice Pellets`,
  7113: $localize`Mostly Clear and Heavy Ice Pellets`,
  7114: $localize`Partly Cloudy and Heavy Ice Pellets`,
  7116: $localize`Mostly Cloudy and Heavy Ice Pellets`,
  7101: $localize`Heavy Ice Pellets`,
  8001: $localize`Mostly Clear and Thunderstorm`,
  8003: $localize`Partly Cloudy and Thunderstorm`,
  8002: $localize`Mostly Cloudy and Thunderstorm`,
  8000: $localize`Thunderstorm`
};
